// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BinCleanerExtension22.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidBinCleanerExtension22PackageString = "086e5092-e511-4011-9651-0357e5247ac5";
        public static Guid guidBinCleanerExtension22Package = new Guid(guidBinCleanerExtension22PackageString);

        public const string guidBinCleanerExtension22PackageCmdSetString = "a6ab2fb9-8dcd-4442-b446-fe92aed67978";
        public static Guid guidBinCleanerExtension22PackageCmdSet = new Guid(guidBinCleanerExtension22PackageCmdSetString);

        public const string guidImagesString = "8471a9c2-9040-4262-85f6-c56b281f21f6";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int BinCleanerId = 0x0100;
        public const int bmpPic1 = 0x0001;
    }
}